
Ecrire un programme qui permet de :
- Déterminer le plus petit commun multiple **PPCM** d'une liste entiers;
- Déterminer le plus grand commun diviseur **PGCD** d'une liste entiers;
- Calculer cos,sin,tan,arcos,arcsin et arctan d'une liste d'angles;
- Calculer la somme,la différence,la multiplication et la division 
  entre deux liste;
- Calculer la puissance et le reste de la division entre deux listes;
- Calculer le rang, la transposée,le determinant,inverse et la trace
  d'une matrice;

- Effectuer les opérations mathématiques sur les éléments d'une
  matrice ;
 
- Résoudre un systèmes d'équations linéaires;

- Calculer les valeurs propres et les vecteurs
  propres d'une matrice.     


In [2]:
import numpy as np

#  PPCM d'une liste entiers

In [28]:
np.lcm(2,4)

4

In [10]:
L=np.array([40,80,60,120])    

In [12]:
L

array([ 40,  80,  60, 120])

In [13]:
x=np.lcm.reduce(L)

In [15]:
print("PPCM: ",x)

PPCM:  240


#  PGCD d'une liste entiers

In [17]:
L=np.array([40,80,60,120])    

In [21]:
# retduit les  éléments de L en leur PGCD
y=np.gcd.reduce(L)

In [22]:
print("PGCD: ",y)

PGCD:  20


# Calculer cos,sin,tan,arcos,arcsin et arctan d'une liste d'angles

In [24]:
np.cos((0))

1.0

In [31]:
# option d'affichage des tableaux numpy
#precision=3: 3 chiffre après la virgule
np.set_printoptions(precision=3)

In [29]:
L= np.array([np.pi,np.pi/2,np.pi/3,np.pi/4])

## cos , sin et tan

In [32]:
#sin
Lsin= np.sin(L)
print(Lsin)

[1.225e-16 1.000e+00 8.660e-01 7.071e-01]


In [33]:
#cos
Lcos= np.cos(L)
print(Lcos)

[-1.000e+00  6.123e-17  5.000e-01  7.071e-01]


In [34]:
#tan
Ltan= np.tan(L)
print(Ltan)

[-1.225e-16  1.633e+16  1.732e+00  1.000e+00]


## arccos , arcsin et arctan

In [36]:
L= np.array([-1,-0.5,-0.1,0,0.1,0.5,1])

In [39]:
#arccos
Larccos= np.arccos(L)
print(Larccos)

[3.142 2.094 1.671 1.571 1.471 1.047 0.   ]


In [40]:
#arcsin
Larcsin= np.arcsin(L)
print(Larcsin)

[-1.571 -0.524 -0.1    0.     0.1    0.524  1.571]


In [41]:
#arctan
Larctan= np.arctan(L)
print(Larctan)

[-0.785 -0.464 -0.1    0.     0.1    0.464  0.785]


#   somme,la différence,la multiplication et la division entre deux liste

In [51]:
L1=np.array([6,7,15,14,12,20])
L2=np.array([3,40,50,9,26,70])

In [45]:
#somme
S=np.add(L1,L2)
print(S)

[ 9 47 65 23 38 90]


In [47]:
#difference
D=np.subtract(L1,L2)
print(D)

[  3 -33 -35   5 -14 -50]


In [48]:
#produit
P=np.multiply(L1,L2)
print(P)

[  18  280  750  126  312 1400]


In [49]:
#division
Dv=np.divide(L1,L2)
print(Dv)

[2.    0.175 0.3   1.556 0.462 0.286]


# Calculer la puissance et le reste de la division entre deux listes

In [57]:
#puissance
L1=np.array([6,7,15,14,12,20])
L2=np.array([2,1,2,2,2,2])
Pu=np.power(L1,L2)
print(Pu)

[ 36   7 225 196 144 400]


In [58]:
#reste de la division
L1=np.array([6,7,15,14,12,20])
L2=np.array([3,40,50,9,26,70])
RD=np.mod(L1,L2)
print(RD)

[ 0  7 15  5 12 20]


# Calculer le rang, la transposée,le determinant,inverse et la trace d'une matrice


In [66]:
M=np.array([
    [1,0,3,0],
    [0,0,4,1],
    [6,0,0,0],
    [4,3,5,3],
])

In [67]:
M.shape

(4, 4)

In [68]:
# Le rang
np.linalg.matrix_rank(M)

4

In [65]:
# transposée
M.transpose()

array([[1, 0, 6],
       [0, 0, 0],
       [3, 4, 0],
       [0, 1, 0]])

In [69]:
# le determinant
np.linalg.det(M)

54.00000000000001

In [70]:
# inverse
np.linalg.inv(M)

array([[ 0.   ,  0.   ,  0.167,  0.   ],
       [ 0.778, -1.   , -0.352,  0.333],
       [ 0.333,  0.   , -0.056,  0.   ],
       [-1.333,  1.   ,  0.222, -0.   ]])

In [71]:
# La trace
np.trace(M)

4

# Effectuer les opérations mathématiques sur les éléments d'une matrice

In [72]:
M

array([[1, 0, 3, 0],
       [0, 0, 4, 1],
       [6, 0, 0, 0],
       [4, 3, 5, 3]])

In [73]:
M+2

array([[3, 2, 5, 2],
       [2, 2, 6, 3],
       [8, 2, 2, 2],
       [6, 5, 7, 5]])

In [74]:
M**2

array([[ 1,  0,  9,  0],
       [ 0,  0, 16,  1],
       [36,  0,  0,  0],
       [16,  9, 25,  9]])

In [75]:
M+M

array([[ 2,  0,  6,  0],
       [ 0,  0,  8,  2],
       [12,  0,  0,  0],
       [ 8,  6, 10,  6]])

In [78]:
M-M

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [81]:
M

array([[1, 0, 3, 0],
       [0, 0, 4, 1],
       [6, 0, 0, 0],
       [4, 3, 5, 3]])

In [80]:
# Produit matriciel
np.matmul(M,M)

array([[19,  0,  3,  0],
       [28,  3,  5,  3],
       [ 6,  0, 18,  0],
       [46,  9, 39, 12]])

# Résoudre un systèmes d'équations linéaires

In [ ]:
# 3x+4y+6z+t=10
# -2x+3y+z-2t=6
# 4x+8y+2z+3t=0
# x-y+z+7t=41

In [89]:
M= np.array([
    [3,4,6,1],
    [-2,3,1,-2],
    [4,8,2,3],
    [1,-1,1,7]
])

N=np.array([10,6,0,41])

In [90]:
x=np.linalg.solve(M,N)
print(x)

[-7.059  0.153  4.043  6.31 ]


# Calculer les valeurs propres et les vecteurs propres d'une matrice   
 

In [91]:
M

array([[ 3,  4,  6,  1],
       [-2,  3,  1, -2],
       [ 4,  8,  2,  3],
       [ 1, -1,  1,  7]])

In [92]:
vals,vects=np.linalg.eig(M)

In [93]:
print("Les valeurs  propres de M sont :", vals)
print("Les vecteurs  propres de M sont : \n", vects)

Les valeurs  propres de M sont : [-3.757+0.j     6.979+1.332j  6.979-1.332j  4.799+0.j   ]
Les vecteurs  propres de M sont : 
 [[-0.528+0.j    -0.183+0.508j -0.183-0.508j -0.764+0.j   ]
 [-0.29 +0.j    -0.311-0.066j -0.311+0.066j  0.057+0.j   ]
 [ 0.797+0.j    -0.142+0.34j  -0.142-0.34j  -0.356+0.j   ]
 [-0.052+0.j     0.687+0.j     0.687-0.j     0.535+0.j   ]]
